version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379" #Exposes Redis on port 6379
    volumes:
      - redis-data:/data #Persists data in a Docker volume

volumes:
  redis-data:
